/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codemercs_iow_IowKit2 */

#ifndef _Included_com_codemercs_iow_IowKit2
#define _Included_com_codemercs_iow_IowKit2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_codemercs_iow_IowKit2_LIB_CLOSED
#define com_codemercs_iow_IowKit2_LIB_CLOSED 0L
#undef com_codemercs_iow_IowKit2_LIB_INIT
#define com_codemercs_iow_IowKit2_LIB_INIT 1L
#undef com_codemercs_iow_IowKit2_LIB_INIT_BUSY
#define com_codemercs_iow_IowKit2_LIB_INIT_BUSY 2L
#undef com_codemercs_iow_IowKit2_LIB_INIT_FAILED
#define com_codemercs_iow_IowKit2_LIB_INIT_FAILED 3L
#undef com_codemercs_iow_IowKit2_LIB_NOT_FOUND
#define com_codemercs_iow_IowKit2_LIB_NOT_FOUND 4L
	/* Inaccessible static: libStatus */
#undef com_codemercs_iow_IowKit2_PIPE_IO_PINS
#define com_codemercs_iow_IowKit2_PIPE_IO_PINS 0L
#undef com_codemercs_iow_IowKit2_PIPE_SPECIAL_MODE
#define com_codemercs_iow_IowKit2_PIPE_SPECIAL_MODE 1L
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_24
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_24 5377LL
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_24PV
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_24PV 5393LL
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_40
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_40 5376LL
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_56			
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_56 5379LL//5394LL
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_28			
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_28 5380LL
#undef com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_100			
#define com_codemercs_iow_IowKit2_PRODUCT_ID_IOWARRIOR_100 5382LL




/* Inaccessible static: deviceListener */
/* Inaccessible static: dataSelectors */
/*
 * Class:     com_codemercs_iow_IowKit2
 * Method:    libraryInitialize
 * Signature: (I)I
 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_libraryInitialize
	(JNIEnv *, jclass, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    libraryFinalize
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_codemercs_iow_IowKit2_libraryFinalize
	(JNIEnv *, jclass);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    setDeviceUse
	 * Signature: (JZ)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_setDeviceUse
	(JNIEnv *, jclass, jlong, jboolean);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getDeviceUse
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_getDeviceUse
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getNumDevs
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit2_getNumDevs
	(JNIEnv *, jclass);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    enumerate
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_codemercs_iow_IowKit2_enumerate
	(JNIEnv *, jclass);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getVersion
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_codemercs_iow_IowKit2_getVersion
	(JNIEnv *, jclass);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    libraryRegister
	 * Signature: (JJII)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_libraryRegister
	(JNIEnv *, jclass, jlong, jlong, jint, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    isConnected
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_isConnected
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    write
	 * Signature: (JI[I)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_write
	(JNIEnv *, jclass, jlong, jint, jintArray);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    read
	 * Signature: (JI[I)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_read
	(JNIEnv *, jclass, jlong, jint, jintArray);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    readNonBlocking
	 * Signature: (JI[I)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_readNonBlocking
	(JNIEnv *, jclass, jlong, jint, jintArray);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    readImmediate
	 * Signature: (J[I)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_readImmediate
	(JNIEnv *, jclass, jlong, jintArray);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    pendingReports
	 * Signature: (JI)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_pendingReports
	(JNIEnv *, jclass, jlong, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    flush
	 * Signature: (JI)I
	 */
	JNIEXPORT jint JNICALL Java_com_codemercs_iow_IowKit2_flush
	(JNIEnv *, jclass, jlong, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getProductId
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit2_getProductId
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getSerialNumber
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit2_getSerialNumber
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getRevision
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit2_getRevision
	(JNIEnv *, jclass, jlong);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    setTimeout
	 * Signature: (JI)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_setTimeout
	(JNIEnv *, jclass, jlong, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    setWriteTimeout
	 * Signature: (JI)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit2_setWriteTimeout
	(JNIEnv *, jclass, jlong, jint);

	/*
	 * Class:     com_codemercs_iow_IowKit2
	 * Method:    getThreadHandle
	 * Signature: (JI)J
	 */
	JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit2_getThreadHandle
	(JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
